name: Run Jolt Scrapper Script

on:
  schedule:
    - cron: '0 6 * * 6'  # Runs at Midnight on Sunday (UTC Time)
  workflow_dispatch:

jobs:
  scrape:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.4'

      #- name: Installing chrome stuff (linux)
      #  run: apt list --installed    
      #- name: Removing previous chrome instances on runner 
      #  run: sudo apt purge google-chrome-stable  
        
      - name: Install packages
        run: | 
          echo "Attempting to install packages"
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install chromedriver-autoinstaller selenium pyvirtualdisplay json
          echo "Succesfully installed 1"
          pip install -api-python-client google-auth-httplib2 google-auth-oauthlib time
          echo "Succesfully installed 2"
          pip install gspread 
          echo "Succesfully installed 3"
        # sudo apt-get install -y xvfb
          

      - name: Chrome setup
        run: |
          python -c "import chromedriver_autoinstaller; chromedriver_autoinstaller.install()"

      - name: Run script
        env:  
          # Secrets needed
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          SERVICE_KEY_JSON_FILE: ${{ secrets.SERVICE_KEY_JSON_FILE }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        run: |
          python jolt_scraper_v4.py
        
